"""Alembic environment.

Two things here are load-bearing:

1. **Every model module is imported explicitly below.** A table only appears in
   `Base.metadata` if its module has been imported, so a module missing from
   that list is silently absent from an autogenerated migration — and the
   failure looks like a missing table at runtime, far from the cause. `api/db.py`
   imports five of the six; `llm_calls` registers only because `api/main.py`
   happens to import `telemetry` first. Do not rely on that here.

2. **The URL comes from `api.config.settings`, not alembic.ini.** One source of
   truth means migrations cannot be run against a different database than the
   app uses.

The engine is async (the app's URL is `sqlite+aiosqlite` / `postgresql+asyncpg`),
so the online path runs through `asyncio.run` and hands Alembic a sync-style
connection via `run_sync`.
"""
import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy.ext.asyncio import async_engine_from_config
from sqlalchemy.pool import NullPool

from api.config import settings
from api.db import Base

# --- model imports: all six, see note 1 above --------------------------------
from api import models  # noqa: F401
from api import telemetry  # noqa: F401
from api.conversation import embeddings  # noqa: F401
from api.conversation import models as conversation_models  # noqa: F401
from api.documents import models as document_models  # noqa: F401
from api.prompts import models as prompt_models  # noqa: F401

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# The app's URL is the default, not an override: an explicitly-configured URL
# wins. That is what lets you point a single run somewhere else —
#   alembic -x ... / Config.set_main_option(...)
# — to rehearse a migration against a scratch database, which is worth doing
# before running one against hosted data. Unset (the normal case) means
# migrations and the app are guaranteed to agree on the target.
if not config.get_main_option("sqlalchemy.url", None):
    config.set_main_option("sqlalchemy.url", settings.database_url)

target_metadata = Base.metadata


def _configure(connection=None, **kw):
    """Shared options for both modes, so they cannot drift apart.

    `render_as_batch` is what makes SQLite migrations work at all: it has no
    real ALTER, so Alembic emulates one by creating a new table, copying rows,
    and swapping. Harmless on Postgres, required on SQLite — and SQLite is the
    self-hoster's database, so it is not a dev-only concern.
    """
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=True,
        render_as_batch=True,
        **kw,
    )


def run_migrations_offline() -> None:
    """Emit SQL to stdout without connecting — for reviewing a migration."""
    _configure(
        url=settings.database_url,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def _run(connection) -> None:
    _configure(connection)
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=NullPool,  # one-shot process; no pool to keep warm
    )
    async with connectable.connect() as connection:
        await connection.run_sync(_run)
    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
